AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false

Metrics:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  # This cop is wrong, `__FILE__` and `__dir__` can't always be substitued
  Enabled: false


Lint/InheritException:
  Enabled: false
