AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false

Metrics:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  # This cop is wrong, `__FILE__` and `__dir__` can't always be substitued
  Enabled: false

Style/CaseEquality:
  Enabled: false # I know what I'm doing, thanks.

Style/GuardClause:
  Enabled: false # Isn't always better.

Style/IfUnlessModifier:
  Enabled: false # Doesn't always make sense.

Style/FormatStringToken:
  Enabled: false # Pointless.

Style/EmptyMethod:
  Enabled: false # Disagree.

Naming/RescuedExceptionsVariableName:
  # Enforcing `e` as an exception name? WTF!
  Enabled: false


Lint/RescueException:
  Enabled: false # I know what I'm doing, thanks.

Lint/InheritException:
  Enabled: false # I know what I'm doing, thanks.

Lint/AssignmentInCondition:
  Enabled: false # I know what I'm doing, thanks.

Security/MarshalLoad:
  Enabled: false # I know what I'm doing, thanks.
